---
- name: Deploy web container remotely
  hosts: webservers
  become: yes

  tasks:
    - name: Stop existing container
      shell: docker stop webcontainer || true

    - name: Remove old container
      shell: docker rm webcontainer || true

    