- name: Deploy web container remotely
  hosts: webservers
  become: true
  tasks:
    - name: Stop existing container
      shell: docker stop webcontainer || true

    - name: Remove old container
      shell: docker rm webcontainer || true

    - name: Run updated container
      shell: docker run -d --name webcontainer -p 8081:80 webimage:latest
