---
- name: Deploy app via Helm
  hosts: web
  become: yes
  tasks:
    - name: Print deployment info
      debug:
        msg: "Deploying app using Helm and Docker image"

    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy latest Docker image details
      copy:
        content: "Image: pintaram369/my-app-image:{{ lookup('env','BUILD_NUMBER') }}"
        dest: /tmp/image_info.txt
